title: SidecarT Docs
description: The SidecarT Developers Documentation site
theme: just-the-docs

url: https://docs.sidecart.xyz

aux_links:
  Template Repository: https://github.com/diegoparrilla/sidecart-site-dev-docs
