title: SidecarT Docs
description: The SidecarT Developers Documentation site
domain: docs.sidecart.xyz

theme: just-the-docs

url: https://docs.sidecart.xyz

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
